name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write

env:
  DEST_DIR: pr-${{ github.event.pull_request.number }}

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          destination_dir: ${{ env.DEST_DIR }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Remove preview directory
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm -rf $DEST_DIR
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}"
            git push origin gh-pages
          fi
